#!/bin/bash
#Menu
cname=$( awk -F: '/model name/ {name=$2} END {print name}' /proc/cpuinfo )
cores=$( awk -F: '/model name/ {core++} END {print core}' /proc/cpuinfo )
freq=$( awk -F: ' /cpu MHz/ {freq=$2} END {print freq}' /proc/cpuinfo )
tram=$( free -m | awk 'NR==2 {print $2}' )
swap=$( free -m | awk 'NR==4 {print $2}' )
up=$(uptime|awk '{ $1=$2=$(NF-6)=$(NF-5)=$(NF-4)=$(NF-3)=$(NF-2)=$(NF-1)=$NF=""; print }')
echo -e "------------------------------------------------------------------------------"
echo -e "\e[032;1mCPU model:\e[0m $cname"
echo -e "\e[032;1mNumber of cores:\e[0m $cores"
echo -e "\e[032;1mCPU frequency:\e[0m $freq MHz"
echo -e "\e[032;1mTotal amount of ram:\e[0m $tram MB"
echo -e "\e[032;1mTotal amount of swap:\e[0m $swap MB"
echo -e "\e[032;1mSystem uptime:\e[0m $up"
echo -e "------------------------------------------------------------------------------"
echo -e "KONFIGURASI SERVER 	:" 
echo -e "+ Open SSH Port : 22"
echo -e "+ Dropbear Port : 109, 110, 22507, 53"
echo -e "+ Stunnel Port : 443"  
echo -e  "+ Squid3 Port : 80, 8080" 
echo -e  "+ Badvpn-udpgw Port : 7300"  
echo -e  "+ OpenVPN TCP Port : 1194 (If Instaled)"  
echo -e  "+ Webmin Port : http://$MYIP:10000/"  
echo -e  "+ Timezone : Asia/Jakarta (GMT +7)"  
echo -e  "+ IPv6 : OFF" 
echo -e  "+ Fail2Ban : ON" 
echo -e "------------------------------------------------------------------------------"
echo -e "COMMAND LIST 	:" 
echo -e "[1]  - Show List Command" 
echo -e "[2]  - Create New Account"
echo -e "[3]  - Create Trial Accout For 1 Day"
echo -e "[4]  - Delete Account" 
echo -e "[5]  - Checking Login Account"
echo -e "[6]  - Checking List Account"
echo -e "[7]  - Restart Service"
echo -e "[8]  - Speedtest Server"
echo -e "[9]  - Server Information"
echo -e "[10] - Edit Banner"
echo -e "[11] - Checking Bandwidth"
echo -e "[12] - Show OpenVPN Configuration (if instaled)"
echo -e "[13] - Edit Fail2ban Configuration (for security)"
echo -e "[0]  - Script Information" 
echo -e "[00] - Reboot Server"
echo -e "Write the number + enter for execution..."
echo -e "------------------------------------------------------------------------------"
echo -e  "Builder : Dey Agustian"  
echo -e  "All Supported by WrgSGntng" 
echo -e  "Thx to  : Fornesia, Rzengineer, Fawzya"  
echo -e "------------------------------------------------------------------------------"
